siteTitle="AI lectures"
baseColor = "#004d40"
linkPrefix = "/"
docPages = [
  "/docs/",
  "/docs/l-1/",
  "/docs/l-2/",
  "/docs/l-3/",
  "/docs/l-4/",
  "/docs/l-5/",
  "/docs/l-6/",
  "/docs/l-7/",
  "/docs/l-8/",
  "/docs/l-9/",
  "/docs/l-10/",
  "/docs/l-11/",
  "/docs/l-12/",
]
